# ============================
# CONFIG: Change settings here
# ============================

seed: 1234567 # Matriculation number Luca Martin

paths:
  project_root: "."
  dataset_root: "./coding_task_data/EuroSAT_RGB"

splits:
  train: "splits/train.txt"
  val: "splits/val.txt"
  test: "splits/test.txt"

training:
  batch_size: 16 # Set the batch size for each training epoch
  num_epochs: 20 # Set the number of epochs
  learning_rate: 0.0001 # Set the learning rate
  augmentation: "mild" # "mild" or "strong"

hardware:
  num_workers: 4
  device: "auto" # "cuda", "cpu", or "auto"

outputs:
  model_dir: "models"
  output_dir: "outputs"
